development: &default
  secret_key_base: <%= ENV["CHAI_SECRET_KEY_BASE"] %>
  datasource_encryptor_secret: <%= ENV["CHAI_DATASOURCE_ENCRYPTOR_SECRET"] %>

test:
  <<: *default

production:
  <<: *default

